const mongoose=require("mongoose")
const OrderSchema=new mongoose.Schema(
    {
       quantity:{
            type:Number,
            required:true,
       },
       customer:{
            type:String,
            required:true,
       },
       farmer:{
            type:String,
            required:true,
       },
       delivery_date:{
            type:String,
            required:true,
       },
       delivery_partner:{
            type:String,
            required:true,
       },
       delivery_status:{
            type:String,
            default:"Pending",
       },
       drop_location:{
            type:String,
            required:true,
       },
       order_date:{
            type:String,
            required:true,
       },
       order_id:{
            type:String,
            required:true,
       },
       pickup_location:{
            type:String,
            required:true,
       },
       product_id:{
            type:String,
            required:true,
       },
    },
    {timestamps:true}
)
module.exports=mongoose.model("Order",OrderSchema)